/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Aluno;
import model.ArrayAluno;
/**
 *
 * @author logonaf
 */

public class InterfaceAluno extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAluno
     */
    
    ArrayAluno array = new ArrayAluno();
    
    public InterfaceAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rgmCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        npCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nrCampo = new javax.swing.JTextField();
        inserirBtn = new javax.swing.JButton();
        btnSel = new javax.swing.JToggleButton();
        resultCampo = new javax.swing.JTextField();
        selCampo = new javax.swing.JTextField();
        btnSelTds = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("RGM:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(rgmCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        jPanel1.add(nomeCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, -1));

        jLabel3.setText("Nota Parcial:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(npCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, -1));

        jLabel4.setText("Nota Regimental:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel1.add(nrCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, -1));

        inserirBtn.setText("Inserir");
        inserirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirBtnActionPerformed(evt);
            }
        });
        jPanel1.add(inserirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btnSel.setText("Selecionar");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });
        jPanel1.add(btnSel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        resultCampo.setEditable(false);
        jPanel1.add(resultCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, 80));

        selCampo.setText("Informe o rgm");
        jPanel1.add(selCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, -1));

        btnSelTds.setText("Selecionar Todos");
        btnSelTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelTdsActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelTds, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirBtnActionPerformed
        String rgm, nome;
        float nota_parc, nota_reg;
        
        rgm = rgmCampo.getText();
        nome = nomeCampo.getText();
        nota_parc = Float.parseFloat(npCampo.getText());
        nota_reg = Float.parseFloat(nrCampo.getText());
        
        Aluno a1 = new Aluno(rgm, nome, nota_parc, nota_reg);
       
        array.inserir(a1);
        
        resultCampo.setText("Aluno inserido com sucesso");
        
    }//GEN-LAST:event_inserirBtnActionPerformed

    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        String rgmAux = selCampo.getText();
        
        if(array.seleciona(rgmAux) != null){
            resultCampo.setText(array.seleciona(rgmAux).getNome() + "\n" + array.seleciona(rgmAux).getRgm() + "\n" + array.seleciona(rgmAux).getNota_parcial() + "\n" + array.seleciona(rgmAux).getNota_reg());
        }
    }//GEN-LAST:event_btnSelActionPerformed

    private void btnSelTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelTdsActionPerformed
        for(Aluno aluno : array.selecionaTodos()) {
            aluno.print();
        }
    }//GEN-LAST:event_btnSelTdsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSel;
    private javax.swing.JButton btnSelTds;
    private javax.swing.JButton inserirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCampo;
    private javax.swing.JTextField npCampo;
    private javax.swing.JTextField nrCampo;
    private javax.swing.JTextField resultCampo;
    private javax.swing.JTextField rgmCampo;
    private javax.swing.JTextField selCampo;
    // End of variables declaration//GEN-END:variables
}
